import type { IdeaStatus } from '../types/domain';

export const LOCATIONS = [
  'Bochnia',
  'Bochnia',
  'Drwinia',
  'Lipnica Murowana',
  'Łapanów',
  'Nowy Wiśnicz',
  'Rzezawa',
  'Trzciana',
  'Żegocina',
  'Borzęcin',
  'Brzesko',
  'Czchów',
  'Dębno',
  'Gnojnik',
  'Iwkowa',
  'Szczurowa',
  'Alwernia',
  'Babice',
  'Chrzanów',
  'Libiąż',
  'Trzebinia',
  'Bolesław',
  'Dąbrowa Tarnowska',
  'Gręboszów',
  'Mędrzechów',
  'Olesno',
  'Radgoszcz',
  'Szczucin',
  'Biecz',
  'Bobowa',
  'Gorlice',
  'Gorlice',
  'Lipinki',
  'Łużna',
  'Moszczenica',
  'Ropa',
  'Sękowa',
  'Uście Gorlickie',
  'Czernichów',
  'Igołomia-Wawrzeńczyce',
  'Iwanowice',
  'Jerzmanowice-Przeginia',
  'Kocmyrzów-Luborzyca',
  'Krzeszowice',
  'Liszki',
  'Michałowice',
  'Mogilany',
  'Skała',
  'Skawina',
  'Słomniki',
  'Sułoszowa',
  'Świątniki Górne',
  'Wielka Wieś',
  'Zabierzów',
  'Zielonki',
  'Dobra',
  'Jodłownik',
  'Kamienica',
  'Laskowa',
  'Limanowa',
  'Limanowa',
  'Łukowica',
  'Mszana Dolna',
  'Mszana Dolna',
  'Niedźwiedź',
  'Słopnice',
  'Szczawa',
  'Tymbark',
  'Charsznica',
  'Gołcza',
  'Kozłów',
  'Książ Wielki',
  'Miechów',
  'Racławice',
  'Słaboszów',
  'Dobczyce',
  'Lubień',
  'Myślenice',
  'Pcim',
  'Raciechowice',
  'Siepraw',
  'Sułkowice',
  'Tokarnia',
  'Wiśniowa',
  'Chełmiec',
  'Gródek nad Dunajcem',
  'Grybów',
  'Grybów',
  'Kamionka Wielka',
  'Korzenna',
  'Krynica-Zdrój',
  'Łabowa',
  'Łącko',
  'Łososina Dolna',
  'Muszyna',
  'Nawojowa',
  'Piwniczna-Zdrój',
  'Podegrodzie',
  'Rytro',
  'Stary Sącz',
  'Czarny Dunajec',
  'Czorsztyn',
  'Jabłonka',
  'Krościenko nad Dunajcem',
  'Lipnica Wielka',
  'Łapsze Niżne',
  'Nowy Targ',
  'Nowy Targ',
  'Ochotnica Dolna',
  'Raba Wyżna',
  'Rabka-Zdrój',
  'Spytkowice',
  'Szaflary',
  'Szczawnica',
  'Nowy Sącz',
  'Bolesław',
  'Bukowno',
  'Klucze',
  'Olkusz',
  'Trzyciąż',
  'Wolbrom',
  'Brzeszcze',
  'Chełmek',
  'Kęty',
  'Osiek',
  'Oświęcim',
  'Oświęcim',
  'Polanka Wielka',
  'Przeciszów',
  'Zator',
  'Koniusza',
  'Koszyce',
  'Nowe Brzesko',
  'Pałecznica',
  'Proszowice',
  'Radziemice',
  'Budzów',
  'Bystra-Sidzina',
  'Jordanów',
  'Jordanów',
  'Maków Podhalański',
  'Stryszawa',
  'Sucha Beskidzka',
  'Zawoja',
  'Zembrzyce',
  'Ciężkowice',
  'Gromnik',
  'Lisia Góra',
  'Pleśna',
  'Radłów',
  'Ryglice',
  'Rzepiennik Strzyżewski',
  'Skrzyszów',
  'Szerzyny',
  'Tarnów',
  'Tuchów',
  'Wierzchosławice',
  'Wietrzychowice',
  'Wojnicz',
  'Zakliczyn',
  'Żabno',
  'Tarnów',
  'Biały Dunajec',
  'Bukowina Tatrzańska',
  'Kościelisko',
  'Poronin',
  'Zakopane',
  'Andrychów',
  'Brzeźnica',
  'Kalwaria Zebrzydowska',
  'Lanckorona',
  'Mucharz',
  'Spytkowice',
  'Stryszów',
  'Tomice',
  'Wadowice',
  'Wieprz',
  'Biskupice',
  'Gdów',
  'Kłaj',
  'Niepołomice',
  'Wieliczka',
  'I Stare Miasto',
  'II Grzegórzki',
  'III Prądnik Czerwony',
  'IV Prądnik Biały',
  'V Krowodrza',
  'VI Bronowice',
  'VII Zwierzyniec',
  'VIII Dębniki',
  'IX Łagiewniki-Borek Fałęcki',
  'X Swoszowice',
  'XI Podgórze Duchackie',
  'XII Bieżanów-Prokocim',
  'XIII Podgórze',
  'XIV Czyżyny',
  'XV Mistrzejowice',
  'XVI Bieńczyce',
  'XVII Wzgórza Krzesławickie',
  'XVIII Nowa Huta',
] as const;

export const IDEA_CATEGORIES = [
  'Bezpieczeństwo',
  'Czystość i odpady',
  'Edukacja',
  'Infrastruktura drogowa',
  'Infrastruktura rowerowa',
  'Kultura',
  'Sport i rekreacja',
  'Tereny zielone',
  'Transport publiczny',
  'Zdrowie i dostępność',
] as const;

export const IDEA_STATUS_OPTIONS: Array<{ value: IdeaStatus; label: string }> =
  [
    { value: 'submitted', label: 'Nowe zgłoszenie' },
    { value: 'under_review', label: 'W analizie' },
    { value: 'accepted', label: 'Przyjęte do realizacji' },
    { value: 'in_progress', label: 'W realizacji' },
    { value: 'completed', label: 'Zrealizowane' },
    { value: 'rejected', label: 'Odrzucone' },
  ];
