import os
import re
from dataclasses import asdict

import psycopg
from psycopg.rows import dict_row
from psycopg import sql



class Database:
    def __init__(self, url=None, *, schema="rops_rag"):
        url = url or os.getenv("DATABASE_URL")
        if not url:
            raise ValueError("Ustaw DATABASE_URL dla PostgreSQL")
        if not re.fullmatch(r"[a-z][a-z0-9_]{0,62}", schema):
            raise ValueError("Niepoprawna nazwa schematu")
        self.schema = schema
        self.connection = psycopg.connect(url, autocommit=True, row_factory=dict_row,
            connect_timeout=10, options=f"-c search_path={schema} -c lock_timeout=5000")
        try:
            self.initialize()
        except Exception:
            self.close()
            raise

    def initialize(self):
        statements = [
            sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(self.schema)),
            "CREATE TABLE IF NOT EXISTS submissions (id TEXT PRIMARY KEY, original_text TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now())",
            "CREATE TABLE IF NOT EXISTS concepts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, problem TEXT NOT NULL, audience TEXT NOT NULL, solution TEXT NOT NULL, category TEXT NOT NULL CHECK (length(btrim(category)) > 0), context TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now())",
            "CREATE TABLE IF NOT EXISTS submission_concepts (submission_id TEXT NOT NULL REFERENCES submissions(id), concept_id BIGINT NOT NULL REFERENCES concepts(id), reason TEXT NOT NULL, PRIMARY KEY(submission_id,concept_id))",
            "CREATE TABLE IF NOT EXISTS concept_embeddings (concept_id BIGINT NOT NULL REFERENCES concepts(id), model TEXT NOT NULL, text_hash TEXT NOT NULL, vector_json TEXT NOT NULL, PRIMARY KEY(concept_id,model))",
            "CREATE TABLE IF NOT EXISTS processing_results (submission_id TEXT PRIMARY KEY REFERENCES submissions(id), result_json TEXT NOT NULL)",
        ]
        with self.connection.transaction():
            for statement in statements:
                self.connection.execute(statement)
            # Nullable for legacy/demo records without an assessment.
            for table in ("submissions", "concepts", "submission_concepts"):
                self.connection.execute(sql.SQL(
                    "ALTER TABLE {} ADD COLUMN IF NOT EXISTS score DOUBLE PRECISION "
                    "CHECK (score >= 0 AND score <= 100)"
                ).format(sql.Identifier(table)))
            constraint = self.connection.execute(
                "SELECT pg_get_constraintdef(oid) AS definition FROM pg_constraint "
                "WHERE conrelid='concepts'::regclass AND conname='concepts_category_check'"
            ).fetchone()
            if constraint and "btrim" not in constraint["definition"]:
                self.connection.execute("ALTER TABLE concepts DROP CONSTRAINT concepts_category_check")
                self.connection.execute("ALTER TABLE concepts ADD CONSTRAINT concepts_category_check CHECK (length(btrim(category)) > 0)")

    def add_submission(self, submission_id, text):
        if not submission_id.strip() or not text.strip():
            raise ValueError("Identyfikator i tekst zgłoszenia są wymagane")
        with self.connection.transaction():
            row = self.connection.execute("INSERT INTO submissions(id,original_text) VALUES (%s,%s) ON CONFLICT(id) DO NOTHING RETURNING id", (submission_id, text)).fetchone()
            if row:
                return True
            old = self.connection.execute("SELECT original_text FROM submissions WHERE id=%s", (submission_id,)).fetchone()
            if old["original_text"] != text:
                raise ValueError("Ten identyfikator należy do innego tekstu zgłoszenia")
            return False

    def insert_concept(self, concept, *, score=None):
        values = asdict(concept)
        values["score"] = score
        return self.connection.execute("INSERT INTO concepts(problem,audience,solution,category,context,score) VALUES (%(problem)s,%(audience)s,%(solution)s,%(category)s,%(context)s,%(score)s) RETURNING id", values).fetchone()["id"]

    def save_match(self, submission_id, *, concept=None, existing_id=None, reason):
        if (concept is None) == (existing_id is None):
            raise ValueError("Podaj concept albo existing_id")
        if not reason.strip():
            raise ValueError("Uzasadnienie jest wymagane")
        with self.connection.transaction():
            cid = self.insert_concept(concept) if concept is not None else existing_id
            self.connection.execute("INSERT INTO submission_concepts(submission_id,concept_id,reason) VALUES (%s,%s,%s) ON CONFLICT(submission_id,concept_id) DO NOTHING", (submission_id, cid, reason))
        return cid

    def list_concepts(self):
        rows = self.connection.execute("SELECT c.*, COUNT(sc.submission_id) AS liczba_zgloszen FROM concepts c LEFT JOIN submission_concepts sc ON sc.concept_id=c.id GROUP BY c.id ORDER BY c.id").fetchall()
        for row in rows:
            row["created_at"] = row["created_at"].isoformat()
        return rows

    def get_concepts_page(self, *, limit=20, offset=0, category=None):
        # Stable snapshot for the count and page, including concurrent submissions.
        where = "WHERE c.category=%s" if category is not None else ""
        params = (category,) if category is not None else ()
        with self.connection.transaction():
            self.connection.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY")
            total = self.connection.execute(
                "SELECT COUNT(*) AS total FROM concepts c " + where, params
            ).fetchone()["total"]
            rows = self.connection.execute(
                "SELECT c.*, (SELECT COUNT(*) FROM submission_concepts sc "
                "WHERE sc.concept_id=c.id) AS liczba_zgloszen FROM concepts c "
                + where + " ORDER BY c.created_at DESC,c.id DESC LIMIT %s OFFSET %s",
                params + (limit, offset),
            ).fetchall()
        for row in rows:
            row["created_at"] = row["created_at"].isoformat()
        return {"items": rows, "total": total, "limit": limit, "offset": offset}

    def get_concept(self, concept_id):
        row = self.connection.execute(
            "SELECT c.*, (SELECT COUNT(*) FROM submission_concepts sc "
            "WHERE sc.concept_id=c.id) AS liczba_zgloszen "
            "FROM concepts c WHERE c.id=%s", (concept_id,),
        ).fetchone()
        if row:
            row["created_at"] = row["created_at"].isoformat()
        return row

    def close(self):
        self.connection.close()
